### ISSUE TITLE
Error loading gblock model - 404 Model not found 

### ISSUE THREAD

**Issue by iburguera** [archilogic-com/aframe-gblock#10]
Since yesterday I'm having issues with gblock on aframe and I'm not able to load the 3D model into a scene. Gblock API replies with "404 model not found" but when you click on the link you can see the model properly. 

![Captura de pantalla 2019-03-13 10 27 17](https://user-images.githubusercontent.com/3015030/54269223-3f7e9680-457d-11e9-90cc-fbf998377208.png)

Libraries versions: 
- https://aframe.io/releases/0.8.2/aframe.min.js
- https://cdn.rawgit.com/archilogic-com/aframe-gblock/6498b71d/dist/gblock.js

The same error occurs on https://gblock.3d.io/

**Comment by tomas-polach** [comment]
This can be fixed by adding a Google Poly API key as described here:
[](https://github.com/archilogic-com/aframe-gblock#usage)
You can get a Google Poly API key here:
[](https://developers.google.com/poly/develop/web#get_an_api_key)

Looks like the API key is now mandatory by Google APIs. I've also updated the demo. Hope this helps?

**Comment by iburguera** [comment]
Creating a Google Poly API Key fixed the issue. 

`<a-entity gblock="https://poly.google.com/view/aba7TBlKyJE?key=GOOGLE_POLY_API_KEY"></a-entity>`
