### ISSUE TITLE
gblock doens't work anymore without poly google key

### ISSUE THREAD

**Issue by PietroMeloni** [archilogic-com/aframe-gblock#11]
I was writing my degree thesis and I saw that gblock wasn't recognizing models anymore (when , like, 1 week ago it was working).
Now I saw you did something to your code.
Does it means that gBlock will not work anymore without poly google key?
What can I do to make it work again?

**Comment by tomas-polach** [comment]
He Pietro, no worries, I will help you out :)

You can get a Google Poly API key here: https://developers.google.com/poly/develop/web#get_an_api_key
Let me know if this helps.

And yes, I had to adapt the code because it stopped working without Google Poly API key. (Details in Issue https://github.com/archilogic-com/aframe-gblock/issues/10)

**Comment by PietroMeloni** [comment]
I solved by adding the key. Thank you!
